module.exports = [
    require('./required'),
    require('./read-only'),
    require('./nullable'),
    require('./type'),
    require('./equals'),
    require('./equalsField'),
    require('./email'),
    require('./oneOf'),
    require('./object-schema'),
    require('./array-schema'),
    require('./pattern'),
    require('./max-length'),
    require('./min-length'),
    require('./integer'),
    require('./min'),
    require('./max'),
    require('./validator')
];
